
# Project name and version
name: 'cowjacket_dbt'
version: '1.0.0'
config-version: 2

# Profile to use
profile: 'default'

# Paths for dbt files
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Where compiled SQL files are stored
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Variables for environment-specific schemas
vars:
  target_schema:
    dev: dbt_dev
    staging: dbt_staging
    prod: dbt_prod

# Configuring models
models:
  cowjacket_dbt:
    # Default materialization for all models
    +materialized: view
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

# Configuring seeds
seeds:
  cowjacket_dbt:
    +quote_columns: true
    +materialized: table
