version: 2

models:
  - name: stg_customers
    description: Cleaned customer records
    columns:
      - name: customer_id
        description: Primary key for customers
        tests:
          - not_null
          - unique
      - name: full_name
        description: Full name of the customer
        tests:
          - not_null
      - name: email
        description: Customer email address
        tests:
          - not_null
          - unique
      - name: join_date
        description: Date the customer joined
        tests:
          - not_null

  - name: stg_products
    description: Cleaned product catalog
    columns:
      - name: product_id
        description: Primary key for products
        tests:
          - not_null
          - unique
      - name: product_name
        description: Name of the product
        tests:
          - not_null
      - name: category
        description: Product category
        tests:
          - not_null
      - name: price
        description: Product price
        tests:
          - not_null

  - name: stg_orders
    description: Cleaned orders data
    columns:
      - name: order_id
        description: Primary key for orders
        tests:
          - not_null
          - unique
      - name: customer_id
        description: Foreign key to customers
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: order_date
        description: Date the order was placed
        tests:
          - not_null
      - name: total_amount
        description: Total order amount
        tests:
          - not_null

  - name: stg_order_items
    description: Line items per order
    columns:
      - name: order_item_id
        description: Primary key for order items
        tests:
          - not_null
          - unique
      - name: order_id
        description: Foreign key to orders
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: product_id
        description: Foreign key to products
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: quantity
        description: Number of products in this line item
        tests:
          - not_null
      - name: line_total
        description: Total amount for this line item
        tests:
          - not_null

  - name: stg_loyalty_points
    description: Customer loyalty point transactions
    columns:
      - name: customer_id
        description: Foreign key to customers
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: points_earned
        description: Points earned in the transaction
        tests:
          - not_null
      - name: transaction_date
        description: Date of transaction
        tests:
          - not_null
      - name: source
        description: Source of the loyalty points
        tests:
          - not_null